name: Build Tauri for Raspberry Pi 3+

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            gcc-aarch64-linux-gnu \
            pkg-config

      - name: Set environment variables
        run: |
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/aarch64-linux-gnu/lib/pkgconfig" >> $GITHUB_ENV

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri app
        run: |
          cargo tauri build --target aarch64-unknown-linux-gnu

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tauri-arm64-build
          path: target/aarch64-unknown-linux-gnu/release/
