name: Build Tauri for Raspberry Pi 3+

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          cpu: cortex-a53

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            gcc-aarch64-linux-gnu \
            pkg-config \
            libssl-dev \
            libgtk-3-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev

      - name: Check openssl path
        run: |
          sudo dpkg -L libssl-dev | grep lib
          sudo dpkg -L libssl-dev | grep include


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-arm64-build
          path: target/aarch64-unknown-linux-gnu/release/
