name: Build Tauri for Raspberry Pi 3+

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: armv8-unknown-linux-gnueabihf

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            gcc-arm-linux-gnueabihf \
            pkg-config

      - name: Set environment variables
        run: |
          echo "CARGO_TARGET_ARMV8_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
          echo "PKG_CONFIG_SYSROOT_DIR=/usr/arm-linux-gnueabihf" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/arm-linux-gnueabihf/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build Tauri app
        run: |
          cargo tauri build --target armv8-unknown-linux-gnueabihf

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-armv8-build
          path: target/armv8-unknown-linux-gnueabihf/release/
